### PR TITLE
Ppunk documents fetch fix #

### LINKED ISSUE #522: Get documents with filters: Invalid value type at `.fields`: expected an array, but found a string
Implode here
https://github.com/meilisearch/meilisearch-php/blob/main/src/Contracts/DocumentsQuery.php#L65

Post request with the fields as string here:
https://github.com/meilisearch/meilisearch-php/blob/main/src/Endpoints/Delegates/HandlesDocuments.php#L30

I'm gonna contribute the fix.

### PR DESCRIPTION
**Pull request by panzer-punk**
Fixes #522 

Fixed behavior for fields if new documents/fetch endpoint used.

### CODE REVIEW

File: src/Contracts/DocumentsQuery.php [hunk 1]
```diff
@@ -56,13 +56,34 @@ public function hasFilter(): bool
...
 
+    /**
+     * Prepares fields for request
+     * Fix for 1.2 document/fetch.
+     *
+     * @see https://github.com/meilisearch/meilisearch-php/issues/522
+     *
+     * @return array|string|null
+     */
+    private function fields(): mixed
```
Comment (brunoocasali) [inline src/Contracts/DocumentsQuery.php:67]: The `mixed` broke the implementation it is only introduced in PHP 8 right? So we can't use that, because we still support php 7.4

```suggestion
    private function fields()
```

**Review by brunoocasali — CHANGES_REQUESTED** [review]
Hi @panzer-punk thanks a lot for your bug fix, I just pointed out something that broke the code.

I'm not sure if there is a replacement, please let me know.

File: src/Contracts/DocumentsQuery.php (hunk 1 above)
Comment (panzer-punk) [reply src/Contracts/DocumentsQuery.php:67]: @brunoocasali yep, my bad. I'll fix it

**Comment by panzer-punk** [comment]
@brunoocasali removed mixed return type

**Comment by brunoocasali** [comment]
bors merge

**Comment by brunoocasali** [comment]
bors merge

**Comment by panzer-punk** [comment]
@brunoocasali I'm not sure what's going on, I just tried to sync fork and I might've broken some checks. bors said there is some integration failure with guzzle 7 and php 7.4. Sorry
