### PR TITLE
Fix passing empty masterkey

### LINKED ISSUE #584: Issue when upgrading from < 1.3 to >= 1.3 with api keys set to empty string
**Description**

PR #514 cleaned up some stuff around the HTTP Client and made some improvements. Unfortunately the PR introduced an breaking change where previously an empty string `''` would not add authorization headers to subsequent api requests to the Meilisearch instance.

e.g. PHP env files at Laravel, this env var would be an empty string:

```
MEILISEARCH_KEY=
```

**Expected behavior**

This code should not add an authorization header to subsequent Meilisearch requests.

```
use Meilisearch\Client;
$meilisearchClient = new Client(
  'http://127.0.0.1:7700',
  '',
);
```

**Current behavior**

The above code adds auth headers to Meilisearch requests.

**Screenshots or Logs**

https://github.com/laravel/scout/issues/769

**Environment (please complete the following information):**
- meilisearch-php version: >= 1.3.0

### PR DESCRIPTION
**Pull request by mmachatschek**
# Pull Request

## Related issue
Fixes #584

## What does this PR do?
- Fix the issue by also checking if the provided masterkey is an empty string

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

File: tests/Http/ClientTest.php [hunk 1]
```diff
@@ -231,6 +231,29 @@ public function testClientHasDefaultUserAgent(): void
         $this->assertTrue($client->isHealthy());
     }
 
+    public function testEmptyMasterkeyRemovesAuthHeader(): void
+    {
+        $httpClient = $this->createHttpClientMock(200, '{}');
+        $reqFactory = $this->createMock(RequestFactoryInterface::class);
+        $requestStub = $this->createMock(RequestInterface::class);
+        $requestStub->expects($this->exactly(1))
```
Comment (norkunas) [inline tests/Http/ClientTest.php:239]:
```suggestion
        $requestStub->expects($this->once())
```

**Comment by mmachatschek** [comment]
@curquiza I didn't revert to the previous behaviour, instead I opted for an check if the user provided an empty string. Empty string can not be passed via authorization anyway so I think this should be safe

**Review by norkunas — DISMISSED** [review]
On new major release I'd leave as is documenting that non-empty-string or null are accepted, so maybe a note for future could be added

File: tests/Http/ClientTest.php [hunk 2]
```diff
@@ -231,6 +231,29 @@ public function testClientHasDefaultUserAgent(): void
...
+    {
+        $httpClient = $this->createHttpClientMock(200, '{}');
+        $reqFactory = $this->createMock(RequestFactoryInterface::class);
+        $requestStub = $this->createMock(RequestInterface::class);
+        $requestStub->expects($this->once())
+            ->method('withAddedHeader')
+            ->willReturnCallback(function ($name, $value) use ($requestStub) {
+                if ('Authorization' === $name) {
+                    $this->assertSame('Bearer ', $value);
+                }
```
Comment (mmachatschek) [inline tests/Http/ClientTest.php:244]: this actually tests the wrong thing. I'll update the test now

Comment (mmachatschek) [reply tests/Http/ClientTest.php]: @norkunas thanks for the suggestion, didn't see the comment while providing a fix 😅 didn't write PHP tests in a while.

Can you check the latest commit?

https://github.com/meilisearch/meilisearch-php/pull/585/commits/dd2d9db35bc5c42d9a298f84ef884f341488a843

**Comment by mmachatschek** [comment]
> On new major release I'd leave as is documenting that non-empty-string or null are accepted, so maybe a note for future could be added

@norkunas I don't quite understand. What do you exactly mean?

File: tests/Http/ClientTest.php (hunk 2 above)
Comment (norkunas) [reply tests/Http/ClientTest.php]: looks good :)

**Comment by norkunas** [comment]
> > On new major release I'd leave as is documenting that non-empty-string or null are accepted, so maybe a note for future could be added
> 
> @norkunas I don't quite understand. What do you exactly mean?

I mean to add a note about https://github.com/meilisearch/meilisearch-php/pull/514#discussion_r1348705607 to not forget it in future :)

File: tests/Http/ClientTest.php (hunk 2 above)
Comment (norkunas) [reply tests/Http/ClientTest.php]: on the second thought, as there is `$this->once()`, the else case will never be reached I think.
so this would be enough:
```
        $requestStub->expects($this->once())
            ->method('withAddedHeader')
            ->willReturnCallback(function ($name, $value) use ($requestStub) {
                $this->assertSame('User-Agent', $name);
                $this->assertSame(Meilisearch::qualifiedVersion(), $value);
```

File: tests/Http/ClientTest.php [hunk 3]
```diff
@@ -231,6 +231,28 @@ public function testClientHasDefaultUserAgent(): void
...
+                $this->assertSame('User-Agent', $name);
+                $this->assertSame(Meilisearch::qualifiedVersion(), $value);
+
+                return $requestStub;
+            });
+        $reqFactory->expects($this->once())
+            ->method('createRequest')
+            ->willReturn($requestStub);
+
+        $client = new \Meilisearch\Client('http://localhost:7070', '', $httpClient, $reqFactory);
```
Comment (norkunas) [inline tests/Http/ClientTest.php:251]:
```suggestion
        $client = new Client('http://localhost:7070', '', $httpClient, $reqFactory);
```

**Review by brunoocasali — APPROVED** [review]
LGTM!

**Comment by norkunas** [comment]
Maybe we should add deprecation?

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
@mmachatschek @norkunas I think the tests are still failing 😕

File: tests/Http/ClientTest.php (hunk 3 above)
Comment (mmachatschek) [reply tests/Http/ClientTest.php]: @norkunas this made the test fail because I specifically was using the `\Meilisearch\Client::class` instead of the `\Meilisearch\Http\Client::class` 😅

**Comment by norkunas** [comment]
Strange to have two Client classes :)

**Review by norkunas — APPROVED** [review]

**Comment by norkunas** [comment]
bors merge
